FROM php:7.4-apache

# Copie des fichiers PHP vers le répertoire du serveur Apache
COPY app/ /var/www/html/

# Installation des dépendances 
RUN docker-php-ext-install mysqli

# Configuration des variables d'environnement pour la connexion à la base de données
ENV DB_HOST=$DB_HOST
ENV DB_NAME$DB_NAME
ENV DB_USER=$DB_USER
ENV DB_PASSWORD=$DB_PASSWORD

# Ajout de la dépendance vers le conteneur MySQL
--link mysql-container:mysql

# Port 80 pour accéder à l'application
EXPOSE 80